name       : telepathy-logger
version    : 0.8.2
release    : 4
source     :
    - http://telepathy.freedesktop.org/releases/telepathy-logger/telepathy-logger-0.8.2.tar.bz2 : 8fcad534d653b1b365132c5b158adae947810ffbae9843f72dd1797966415dae
license    : GPL-2.0
component  : desktop.library
summary    : Telepathy logging service
description: |
    Telepathy Logger is a platform-independent logging service for the Telepathy communications framework.
builddeps  :
    - pkgconfig(sqlite3)
    - pkgconfig(telepathy-glib)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
